[env:esp32wroom]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
build_flags =
    -D CORE_DEBUG_LEVEL=1
